name: TwicussEconomy
version: '${project.version}'
main: net.ddns.twicusstumble.twicusseconomy.TwicussEconomy
authors: [ RED_wing ]
description: Add the concept of "shuff" economics to the game.
commands:
  te:
permissions:
  twicusseconomics.admin:
    default: op